Account path
hiqdev/hipanel-module-hosting pull request #1
Opened 2017-05-25 14:42 UTC by bladeroot

2017-05-25 15:18 UTC, hiqsol requested changes

2017-05-25 15:18 UTC, hiqsol commented on src/controllers/AccountController.php
> +                'findOptions' => ['with_directories' => true, 'limit' => 'ALL'],
уверен на счёт ALL ?

2017-05-25 15:18 UTC, hiqsol commented on src/controllers/AccountController.php
> +                        if ($pathLike !== null) {
мне кажется именно здесь уместнее будет `if ($pathLike) {`

2017-05-26 08:57 UTC, bladeroot commented on src/controllers/AccountController.php
> +                        if ($pathLike !== null) {
Нет, если выполняется запрос и не введене ничего в поле, то переменная pathLike = null. С другой стороны может и имеет. Сделаю if ($pathLike) {

2017-05-26 08:57 UTC, bladeroot commented on src/controllers/AccountController.php
> +                'findOptions' => ['with_directories' => true, 'limit' => 'ALL'],
Не совсем. Но этот же параметр я добавил и в апи. Так что все же спорно. Хотя, так как фильтра по директориям нет (встроенного в запрос), то решение спорное

2017-05-26 09:02 UTC, bladeroot commented on src/controllers/AccountController.php
> +                'findOptions' => ['with_directories' => true, 'limit' => 'ALL'],
Проврил. Реально ALL в апи только надо было. Убрал.

2017-05-26 09:04 UTC, merged