added ghost settings and system settings props updating in account
hiqdev/hipanel-module-hosting pull request #34
Opened 2019-10-16 10:12 UTC by strorch

2019-10-17 09:10 UTC, SilverFire commented on src/controllers/AccountController.php
> +                            $kek = 1;
lol

2019-10-21 11:48 UTC, strorch commented
moved mail settings from Account to AccountValues model

2019-10-21 16:42 UTC, hiqsol requested changes

2019-10-21 16:42 UTC, hiqsol commented on src/views/account/_setSystemSettings.php
> +                <legend><?= Yii::t('hipanel:hosting:account', 'Enter system settings') ?></legend>
Давай без enter

2019-10-21 16:42 UTC, hiqsol commented on src/views/account/_setGhostOptions.php
> +            <legend><?= Yii::t('hipanel:hosting:account', 'Enter global vhost options') ?></legend>
Давай без enter

2019-10-21 16:42 UTC, hiqsol commented on src/messages/ru/hipanel:hosting:account.php
> +    'Enter system settings' => 'Введите системные настройки',
тут тоже без Enter

2019-10-29 14:05 UTC, tafid requested changes

2019-10-29 14:05 UTC, tafid commented on src/models/Account.php
> +            [['path', 'gid', 'uid'], 'safe', 'on' => ['set-system-settings']],
а может не "safe"?

2019-10-29 14:47 UTC, SilverFire approved these changes

2019-10-29 14:47 UTC, merged