Applied PTR change if role support and lower
hiqdev/hipanel-module-hosting pull request #37
Opened 2020-04-01 15:14 UTC by tafid

2020-04-01 16:38 UTC, hiqsol requested changes

2020-04-01 16:38 UTC, hiqsol commented on src/models/Ip.php
> +        if ($user->can('role:manager') || $user->can('role:support')) {
can(role) - неправильно, должно быть can(permission)

2020-04-02 10:22 UTC, SilverFire approved these changes

2020-04-02 10:24 UTC, SilverFire approved these changes

2020-04-02 10:35 UTC, merged