Added `EasyAccessControl` to BackupController.php, BackupingControlle…
hiqdev/hipanel-module-hosting pull request #8
Opened 2018-04-30 15:13 UTC by pkolomiy

…r.php, CrontabController.php, HdomainController.php, MailController.php and VhostController.php

2018-04-30 15:47 UTC, SilverFire requested changes

2018-04-30 15:47 UTC, SilverFire commented on src/controllers/VhostController.php
> +                    '*' => 'account.read',
Для advanced-config, manage-proxy нужно account.update

2018-05-02 07:48 UTC, SilverFire requested changes

2018-05-02 07:48 UTC, SilverFire commented on src/controllers/VhostController.php
> +                    'advanced-config,manage-proxy' => 'account.update',
Такой синтаксис не работает. Каждый экшен – отдельный элемент массива

2018-05-02 07:57 UTC, pkolomiy commented on src/controllers/VhostController.php
> +                    'advanced-config,manage-proxy' => 'account.update',
Тогда нужно будет исправить и в других файлах, как например [тут](https://github.com/hiqdev/hipanel-module-finance/blob/b35973704c92a2d9ee4c0f07ddf4f0a61a87a111/src/controllers/TariffController.php#L33)

2018-05-02 08:07 UTC, SilverFire commented on src/controllers/VhostController.php
> +                    'advanced-config,manage-proxy' => 'account.update',
Да, я ошибся, сорри

2018-05-02 08:07 UTC, merged